# Generated by Django 5.2.14 on 2026-05-29 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('trash', 'Trash'), ('restore', 'Restore'), ('delete', 'Delete'), ('force_delete', 'Force delete')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('view_all', 'View all'), ('view_single', 'View single'), ('view_own', 'View own / personal'), ('create', 'Create'), ('edit', 'Edit'), ('edit_own', 'Edit own / personal'), ('delete_all', 'Delete all'), ('delete_own', 'Delete own / personal'), ('trash', 'Trash'), ('trash_own', 'Trash own / personal'), ('restore', 'Restore'), ('restore_own', 'Restore own / personal'), ('force_delete', 'Force delete'), ('force_delete_own', 'Force delete own / personal')], max_length=50)),
                ('level', models.CharField(choices=[('all', 'All / director level'), ('own', 'Own / personal level'), ('single', 'Single record level')], default='all', max_length=50)),
                ('codename', models.CharField(max_length=150, unique=True)),
                ('label_en', models.CharField(max_length=200)),
                ('label_dari', models.CharField(blank=True, max_length=200)),
                ('label_pashto', models.CharField(blank=True, max_length=200)),
                ('label_arabic', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['app_label', 'model_name', 'action', 'level'],
                'unique_together': {('app_label', 'model_name', 'action', 'level')},
            },
        ),
    ]
